/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI; 

import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author MANH.TD194616
 */
public class PersonalPage extends javax.swing.JFrame {

    /**
     * Creates new form PersonalPage
     */
    public PersonalPage() {
        initComponents();
        loadData();
    }


    private void loadData() {
        try {
            Connect a = new Connect();
            Connection con = a.getConnectDB();
            PreparedStatement ps = con.prepareStatement("select staff_id, \n"
                    + "sales.staffs.name, \n"
                    + "sales.staffs.email, \n"
                    + "sales.staffs.phone, \n"
                    + "active, \n"
                    + "sales.stores.name, \n"
                    + "manager_state, \n"
                    + "gender "
                    + "from sales.staffs "
                    + "inner join sales.stores on sales.staffs.store_id = sales.stores.store_id\n"
                    + "where staff_id = ?");
            ps.setString(1, Login.Staff_ID);
            ResultSet rs = ps.executeQuery();

            rs.next();
            txtID.setText(rs.getString(1));
            txtName.setText(rs.getString(2));
            txtEmail.setText(rs.getString(3));
            txtPhone.setText(rs.getString(4));
            
            txtStore.setText(rs.getString(6));
            if (rs.getString(7).equals("1")) {
                txtLevel.setText("Quản lý");
            } else {
                txtLevel.setText("Nhân viên");
            }
            txtGender.setText(rs.getString(8));

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtPhone = new javax.swing.JLabel();
        txtStore = new javax.swing.JLabel();
        txtLevel = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(643, 423));
        setPreferredSize(new java.awt.Dimension(643, 423));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thông tin cá nhân");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 90, 240, 30);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtID.setText("a");
        getContentPane().add(txtID);
        txtID.setBounds(170, 130, 160, 30);

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.setText("a");
        getContentPane().add(txtName);
        txtName.setBounds(170, 170, 160, 30);

        txtGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGender.setText("a");
        getContentPane().add(txtGender);
        txtGender.setBounds(170, 200, 150, 30);

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhone.setText("a");
        getContentPane().add(txtPhone);
        txtPhone.setBounds(170, 230, 140, 30);

        txtStore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStore.setText("a");
        getContentPane().add(txtStore);
        txtStore.setBounds(170, 260, 160, 30);

        txtLevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLevel.setText("a");
        getContentPane().add(txtLevel);
        txtLevel.setBounds(170, 300, 160, 30);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(420, 140, 160, 24);

        jButton1.setText("Đổi mật khẩu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 170, 120, 40);

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 260, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thông tin cá nhân (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Reset rs = new Reset(txtEmail.getText());
        rs.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
        if (Login.manager_state == 1){
            Main_QuanLy main = new Main_QuanLy();
            main.setVisible(true); 
        } else {
            Main_NhanVien main = new Main_NhanVien();
            main.setVisible(true); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtLevel;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtStore;
    // End of variables declaration//GEN-END:variables
}
